services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.react_app
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:9999"
    restart: always
    env_file:
      - .env
